version: '3.8'

services:

  python:
    build:
      context: ./docker/python
    container_name: python_service
    volumes:
      - ./python:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null  # Mantener el contenedor en ejecución
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017/mi_db
    networks:
      - custom_network
    depends_on:
      - mongo
  
  
  mongo:
    image: mongo:6.0
    container_name: mongo_service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - custom_network



volumes:
  mongo-data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1